/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Common.StaticData;
import Db.DatabaseQueries;
import Modal.Account;
import javax.swing.JOptionPane;

/**
 *
 * @author SSC
 */
public class ClientHomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClientHomeFrame
     */
    private Account currentAccount;

    public ClientHomeFrame() {
        initComponents();
      //  StaticData.resizeLabelImage(StaticData.getImage(StaticData.BackGroundImages.SIMPLEBACKGROUND), backgroundImage);
        StaticData.resizeLabelImage(StaticData.getImage(StaticData.BackGroundImages.CLIENTLOGO), loginlogo);
        currentAccount = DatabaseQueries.getAccountDataByClientUserName(StaticData.loginUserInfo.getUserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginlogo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        transferBButton = new javax.swing.JButton();
        transactionsButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        updateProfile1 = new javax.swing.JButton();
        balanceButton = new javax.swing.JButton();
        depositButton = new javax.swing.JButton();
        withdrawButton = new javax.swing.JButton();
        complainButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client Home - Banking App");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginlogo.setText("                      loginlogo");
        getContentPane().add(loginlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 180, 180));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 70)); // NOI18N
        jLabel5.setText("Client Home");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        transferBButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        transferBButton.setText("Transfer");
        transferBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferBButtonActionPerformed(evt);
            }
        });
        getContentPane().add(transferBButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 160, 40));

        transactionsButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        transactionsButton.setText("Transactions");
        transactionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(transactionsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 160, 40));

        logoutButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 160, 40));

        updateProfile1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        updateProfile1.setText("View Profile");
        updateProfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfile1ActionPerformed(evt);
            }
        });
        getContentPane().add(updateProfile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 160, 40));

        balanceButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        balanceButton.setText("Balance ");
        balanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(balanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 160, 40));

        depositButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        depositButton.setText("Deposit");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });
        getContentPane().add(depositButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 160, 40));

        withdrawButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        withdrawButton.setText("WithDraw");
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });
        getContentPane().add(withdrawButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 160, 40));

        complainButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        complainButton.setText("Complain");
        complainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complainButtonActionPerformed(evt);
            }
        });
        getContentPane().add(complainButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 160, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void transferBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferBButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TransferFrame().setVisible(true);
    }//GEN-LAST:event_transferBButtonActionPerformed

    private void transactionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ViewTransactionHistoryForClientFrame().setVisible(true);

    }//GEN-LAST:event_transactionsButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void updateProfile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfile1ActionPerformed
        // TODO add your handling code here:
        new ViewCompleteClientInfoFrame(StaticData.loginUserInfo.getUserName()).setVisible(true);
    }//GEN-LAST:event_updateProfile1ActionPerformed

    private void balanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceButtonActionPerformed
        // TODO add your handling code here:

        JOptionPane.showConfirmDialog(null, "Your Current Balance is ₪ : " + currentAccount.getBalance(), "Current Balance", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_balanceButtonActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DepositFrame().setVisible(true);
    }//GEN-LAST:event_depositButtonActionPerformed

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new WithdrawFrame().setVisible(true);
    }//GEN-LAST:event_withdrawButtonActionPerformed

    private void complainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complainButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complainButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balanceButton;
    private javax.swing.JButton complainButton;
    private javax.swing.JButton depositButton;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel loginlogo;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton transactionsButton;
    private javax.swing.JButton transferBButton;
    private javax.swing.JButton updateProfile1;
    private javax.swing.JButton withdrawButton;
    // End of variables declaration//GEN-END:variables
}
