/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Common.StaticData;
import Db.DatabaseQueries;

/**
 *
 * @author SSC
 */
public class ReciptFrame extends javax.swing.JFrame {

    /**
     * Creates new form ReciptFrame
     */
    public ReciptFrame() {
        initComponents();
        StaticData.resizeLabelImage(StaticData.getImage(StaticData.BackGroundImages.SIMPLEBACKGROUND), backgroundImage);

    }

    public ReciptFrame(String method, String _message) {
        super(method + " Recipt - Banking App");
        initComponents();
        StaticData.resizeLabelImage(StaticData.getImage(StaticData.BackGroundImages.SIMPLEBACKGROUND), backgroundImage);

        if (method.toUpperCase().compareTo("DEPOSIT") == 0) {
            remainingLimit.setVisible(false);
        } else {
            double todaySpentAmount = DatabaseQueries.getTotalTransactionAmountOfSpecificType(StaticData.currentClientAccountInfo.getAccountNumber(), method.toUpperCase());
            if (method.toUpperCase().compareTo("WITHDRAW") == 0) {
                remainingLimit.setText("Your remaing today withdraw limit is  ₪ : " + (StaticData.currentClientAccountInfo.getWithdrawLimit() - todaySpentAmount));
            } else {
                remainingLimit.setText("Your remaing today transfer limit is  ₪ : " + (StaticData.currentClientAccountInfo.getTransferLimit() - todaySpentAmount));
            }
        }
        heading.setText(method + " Successfull");
        balance.setText("Your Current Balance is ₪ : " + StaticData.currentClientAccountInfo.getBalance());
        message.setText(_message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        remainingLimit = new javax.swing.JLabel();
        heading = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recipt - Banking App");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        remainingLimit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        remainingLimit.setText("Deposit");
        getContentPane().add(remainingLimit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 660, 40));

        heading.setFont(new java.awt.Font("Agency FB", 1, 70)); // NOI18N
        heading.setText("Deposit");
        getContentPane().add(heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 590, -1));

        message.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        message.setText("Deposit");
        getContentPane().add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 700, 40));

        balance.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        balance.setText("Deposit");
        getContentPane().add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 660, 40));

        okButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 270, 30));

        backgroundImage.setText("jLabel1");
        getContentPane().add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ReciptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ReciptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ReciptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ReciptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ReciptFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JLabel balance;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel message;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel remainingLimit;
    // End of variables declaration//GEN-END:variables
}
