/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Common.StaticData;
import Db.DatabaseQueries;
import Modal.Account;
import Modal.Login;
import Modal.Transfer;
import javax.swing.JOptionPane;

/**
 *
 * @author SSC
 */
public class TransferVerificationFrame extends javax.swing.JFrame {

    /**
     * Creates new form TransferVerificationFrame
     */
    private Account senderAccount;
    private double balance;

    public TransferVerificationFrame(String accountNumber, double bal) {
        initComponents();
        StaticData.resizeLabelImage(StaticData.getImage(StaticData.BackGroundImages.SIMPLEBACKGROUND), backgroundImage);

        senderAccount = DatabaseQueries.getAccountDataByAccountNumber(accountNumber);
        balance = bal;
        this.accountNumber.setText(accountNumber);
        username2.setText(senderAccount.getClientUsername());
        Login temp = DatabaseQueries.getUserByUsername(senderAccount.getClientUsername());
        completeName.setText(temp.getFirstName() + " " + temp.getLastName());
        amount.setText("" + balance);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading = new javax.swing.JLabel();
        accountNumber = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        username2 = new javax.swing.JLabel();
        completeName = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        proceedButton = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        heading.setFont(new java.awt.Font("Agency FB", 1, 70)); // NOI18N
        heading.setText("Transfer Verification");
        getContentPane().add(heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 540, -1));

        accountNumber.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        accountNumber.setForeground(new java.awt.Color(102, 102, 255));
        accountNumber.setText("Account Number");
        accountNumber.setToolTipText("Login");
        getContentPane().add(accountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 320, 30));

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel15.setText("Account Number");
        jLabel15.setToolTipText("Login");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 190, 30));

        username.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        username.setForeground(new java.awt.Color(102, 102, 255));
        username.setText("Account Number");
        username.setToolTipText("Login");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 260, 30));

        username2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        username2.setText("Username");
        username2.setToolTipText("Login");
        getContentPane().add(username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 190, 30));

        completeName.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        completeName.setForeground(new java.awt.Color(102, 102, 255));
        completeName.setText("Account Number");
        completeName.setToolTipText("Login");
        getContentPane().add(completeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 320, 30));

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel19.setText("Name");
        jLabel19.setToolTipText("Login");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 190, 30));

        amount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        amount.setForeground(new java.awt.Color(102, 102, 255));
        amount.setText("Account Number");
        amount.setToolTipText("Login");
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 300, 30));

        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel21.setText("Amount");
        jLabel21.setToolTipText("Login");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 190, 30));

        cancelButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 250, 30));

        proceedButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        proceedButton.setText("Proceed");
        proceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedButtonActionPerformed(evt);
            }
        });
        getContentPane().add(proceedButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 250, 30));

        backgroundImage.setText("jLabel1");
        getContentPane().add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ClientHomeFrame().setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void proceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedButtonActionPerformed
        // TODO add your handling code here:
        int row = DatabaseQueries.insertTransactionData(new Transfer(0, StaticData.currentClientAccountInfo.getAccountNumber(), senderAccount.getAccountNumber(), null, null, balance));
        if (row > 0) {
            StaticData.currentClientAccountInfo = DatabaseQueries.getAccountDataByClientUserName(StaticData.loginUserInfo.getUserName());
            this.dispose();
            new ReciptFrame("TRANSFER", "₪ : " + balance + " has been successfully transfer from your account to acc#" + accountNumber.getText() + "."
            ).setVisible(true);
            new ClientHomeFrame().setVisible(true);
        } else {
            JOptionPane.showConfirmDialog(null, "Amount not Transfer", "Transfer Errors", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_proceedButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNumber;
    private javax.swing.JLabel amount;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel completeName;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JButton proceedButton;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username2;
    // End of variables declaration//GEN-END:variables
}
