/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Common.StaticData;
import Db.DatabaseQueries;
import Modal.Transfer;
import javax.swing.JOptionPane;

/**
 *
 * @author SSC
 */
public class TransferFrame extends javax.swing.JFrame {

    /**
     * Creates new form TransferFrame
     */
    public TransferFrame() {
        initComponents();
        StaticData.resizeLabelImage(StaticData.getImage(StaticData.BackGroundImages.SIMPLEBACKGROUND), backgroundImage);
        StaticData.resizeButtonImage(StaticData.getImage(StaticData.BackGroundImages.HOMELOGO), homeButton, homeButton.getWidth() - 10, homeButton.getHeight() - 8);
        StaticData.resizeButtonImage(StaticData.getImage(StaticData.BackGroundImages.LOGOUTLOGO), logoutButton, 30, logoutButton.getHeight() - 8);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        transferAmount = new javax.swing.JTextField();
        transferButton = new javax.swing.JButton();
        accountNumber = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();
        backgrountImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transfer - Banking App");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, 30));

        logoutButton.setBackground(new java.awt.Color(255, 255, 255));
        logoutButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        logoutButton.setText("ogout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 110, 30));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 70)); // NOI18N
        jLabel5.setText("Transfer");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel13.setText("Transfer Amount");
        jLabel13.setToolTipText("Login");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 190, -1));

        transferAmount.setToolTipText("Deposit Amount");
        transferAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferAmountActionPerformed(evt);
            }
        });
        getContentPane().add(transferAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 230, 30));

        transferButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        transferButton.setText("Transfer");
        transferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButtonActionPerformed(evt);
            }
        });
        getContentPane().add(transferButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 270, 30));

        accountNumber.setToolTipText("Deposit Amount");
        accountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNumberActionPerformed(evt);
            }
        });
        getContentPane().add(accountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 230, 30));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel14.setText("Account Number");
        jLabel14.setToolTipText("Login");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 190, -1));

        backgroundImage.setText("jLabel1");
        getContentPane().add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 340));

        backgrountImage.setText("jLabel1");
        getContentPane().add(backgrountImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ClientHomeFrame().setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void transferAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferAmountActionPerformed

    private void transferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButtonActionPerformed
        // TODO add your handling code here:
        if (accountNumber.getText().equals("")) {
            JOptionPane.showConfirmDialog(null, "Enter Account Number", "Account Number Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            
        } else if (DatabaseQueries.getAccountDataByAccountNumber(accountNumber.getText()) == null) {
            JOptionPane.showConfirmDialog(null, "Account Number Not Valid", "Account Number Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            
        } else {
            double depAmount = StaticData.getAndValidatePrice(transferAmount.getText(), "Transfer Amount");
            double remainingDailyLimit = StaticData.currentClientAccountInfo.getTransferLimit() - DatabaseQueries.getTotalTransactionAmountOfSpecificType(StaticData.currentClientAccountInfo.getAccountNumber(), "TRANSFER");
            
            if (depAmount <= 0) {
                
            } else if (depAmount > StaticData.currentClientAccountInfo.getTransferLimit()) {
                JOptionPane.showConfirmDialog(null, "Your transfer limit is ₪ : " + StaticData.currentClientAccountInfo.getTransferLimit() + ". Kindly enter amount within that limit.", "Transfer MAx Limit Errors", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
                
            } else if (depAmount > remainingDailyLimit) {
                JOptionPane.showConfirmDialog(null, "Your today transfer remaining limit is ₪ : " + remainingDailyLimit + ". Kindly enter amount within that limit.", "Transfer MAx Limit Errors", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            } else {
                this.dispose();
                new TransferVerificationFrame(accountNumber.getText(), depAmount).setVisible(true);
            }
        }
    }//GEN-LAST:event_transferButtonActionPerformed

    private void accountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNumberActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNumber;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JLabel backgrountImage;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField transferAmount;
    private javax.swing.JButton transferButton;
    // End of variables declaration//GEN-END:variables
}
