/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Common.StaticData;
import Db.DatabaseQueries;
import Modal.Account;
import Modal.Client;
import Modal.Login;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author SSC
 */
public class UpdateClientFrame extends javax.swing.JFrame {

    /**
     * Creates new form UpdateClientFrame
     */
    public UpdateClientFrame() {
        initComponents();
    }
    private Login userInfo;
    private Account accountInfo;
    ButtonGroup btg = new ButtonGroup();

    public UpdateClientFrame(String clientusername, int ty) {
        if (ty == 2) {
            super.setTitle("Update Account - Banking App");
        }
        initComponents();
        if (ty == 2) {
            heading.setText("Update Account");
            updateButton.setText("Update Account");
        }
        btg.add(currentAccount);
        btg.add(savingAccont);
        userInfo = DatabaseQueries.getUserByUsername(clientusername);
        accountInfo = DatabaseQueries.getAccountDataByClientUserName(clientusername);
        StaticData.resizeLabelImage(StaticData.getImage(StaticData.BackGroundImages.SIMPLEBACKGROUND), backgroundImage);
        StaticData.resizeButtonImage(StaticData.getImage(StaticData.BackGroundImages.HOMELOGO), homeButton, homeButton.getWidth() - 10, homeButton.getHeight() - 8);
        StaticData.resizeButtonImage(StaticData.getImage(StaticData.BackGroundImages.LOGOUTLOGO), logoutButton, 30, logoutButton.getHeight() - 8);

        accountNumber.setEnabled(false);
        username.setEnabled(false);
        if (userInfo != null && accountInfo != null) {
            accountNumber.setText(accountInfo.getAccountNumber());
            firstname.setText(userInfo.getFirstName());
            lastname.setText(userInfo.getLastName());
            username.setText(userInfo.getUserName());
            password.setText(userInfo.getPassword());
            balance.setText("₪ : " + accountInfo.getBalance());
            transferAmountLimit.setText("" + accountInfo.getTransferLimit());
            withDrawAmountLimit.setText("" + accountInfo.getWithdrawLimit());
            System.out.println(accountInfo.getAccountTypeId());
            if (DatabaseQueries.getAccountTypeById(accountInfo.getAccountTypeId()).getName().equals("Current Account")) {
                currentAccount.setSelected(true);
                savingAccont.setSelected(false);
            } else {
                currentAccount.setSelected(false);
                savingAccont.setSelected(true);
            }
            if (accountInfo.getStatus().equals("ACTIVE")) {
                accountStatus.setSelectedIndex(0);
            } else {
                accountStatus.setSelectedIndex(1);
            }
        } else {
            JOptionPane.showConfirmDialog(null, "Some error for fetching data", "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accountNumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        withDrawAmountLimit = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        transferAmountLimit = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        currentAccount = new javax.swing.JRadioButton();
        savingAccont = new javax.swing.JRadioButton();
        updateButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        accountStatus = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Client - Banking App");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        heading.setFont(new java.awt.Font("Agency FB", 1, 70)); // NOI18N
        heading.setText("Update Client");
        getContentPane().add(heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 380, 70));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setText("Account #");
        jLabel2.setToolTipText("Login");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        accountNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(accountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 210, 30));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel11.setText("Username ");
        jLabel11.setToolTipText("Login");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        username.setToolTipText("Login");
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 200, 30));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setText("Password");
        jLabel3.setToolTipText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        password.setToolTipText("Login");
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 210, 30));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel6.setText("LastName");
        jLabel6.setToolTipText("LastName");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        lastname.setToolTipText("LastName");
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        getContentPane().add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 210, 30));

        firstname.setToolTipText("First Name");
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        getContentPane().add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 200, 30));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel7.setText("First Name");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Limits", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        withDrawAmountLimit.setToolTipText("Withdraw Limit");
        withDrawAmountLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withDrawAmountLimitActionPerformed(evt);
            }
        });
        jPanel1.add(withDrawAmountLimit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 210, 30));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel10.setText("Withdraw");
        jLabel10.setToolTipText("Login");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        transferAmountLimit.setToolTipText("Transfer Limit");
        transferAmountLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferAmountLimitActionPerformed(evt);
            }
        });
        jPanel1.add(transferAmountLimit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 200, 30));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel13.setText("Transfer");
        jLabel13.setToolTipText("Login");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 690, 100));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel4.setText("Status:");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        currentAccount.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        currentAccount.setSelected(true);
        currentAccount.setText("Current Account");
        getContentPane().add(currentAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        savingAccont.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        savingAccont.setText("Saving Account");
        getContentPane().add(savingAccont, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        updateButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 210, 30));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel12.setText("Account Type");
        jLabel12.setToolTipText("");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        accountStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        accountStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVE", "BLOCKED" }));
        getContentPane().add(accountStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 200, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel8.setText("Balance:");
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, -1, -1));

        balance.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        balance.setText("₪ : 10000");
        balance.setToolTipText("");
        getContentPane().add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, -1));

        homeButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 30));

        logoutButton.setBackground(new java.awt.Color(255, 255, 255));
        logoutButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        logoutButton.setText("ogout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 110, 30));

        backgroundImage.setText("jLabel1");
        getContentPane().add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void withDrawAmountLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withDrawAmountLimitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withDrawAmountLimitActionPerformed

    private void transferAmountLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferAmountLimitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferAmountLimitActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        if ("".equals(username.getText())) {
            JOptionPane.showConfirmDialog(null, "Enter username", "Username Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
        } else if (password.getText().equals("")) {
            JOptionPane.showConfirmDialog(null, "Enter password", "Password Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
        } else if (firstname.getText().equals("")) {
            JOptionPane.showConfirmDialog(null, "Enter firstname", "Firstname Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
        } else if (lastname.getText().equals("")) {
            JOptionPane.showConfirmDialog(null, "Enter Lastname", "Lastname Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
        } else if (StaticData.getAndValidatePrice(transferAmountLimit.getText(), "Transfer Amount Limit") <= 0
                || StaticData.getAndValidatePrice(withDrawAmountLimit.getText(), "Withdraw Amount Limit") <= 0) {
        } else {
            int row = DatabaseQueries.updateClientData(new Client(username.getText(), password.getText(), firstname.getText(), lastname.getText()));
            if (row > 0) {
                int accountTypeId = 1;

                try {
                    accountTypeId = currentAccount.isSelected() ? DatabaseQueries.getAccountTypeByName("Current Account").getId() : DatabaseQueries.getAccountTypeByName("Saving Account").getId();
                } catch (Exception e) {
                    System.out.println("Account it derror : " + accountTypeId);
                }
                row = DatabaseQueries.updateAccountData(new Account(accountNumber.getText(), username.getText(), null, accountTypeId, 0, StaticData.getAndValidatePrice(transferAmountLimit.getText(), "Transfer Amount Limit"), StaticData.getAndValidatePrice(withDrawAmountLimit.getText(), "Withdraw Amount Limit"), accountStatus.getSelectedItem().toString()));
                if (row > 0) {
                    JOptionPane.showConfirmDialog(null, "Client and Account updated Successfully", "Success", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    new ViewClientFrame().setVisible(true);
                } else {
                    JOptionPane.showConfirmDialog(null, "Account not update", "Account Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showConfirmDialog(null, "Client not updated", "Client Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdminHomeFrame().setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UpdateClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UpdateClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UpdateClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UpdateClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UpdateClientFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNumber;
    private javax.swing.JComboBox<String> accountStatus;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JLabel balance;
    private javax.swing.JRadioButton currentAccount;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel heading;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastname;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField password;
    private javax.swing.JRadioButton savingAccont;
    private javax.swing.JTextField transferAmountLimit;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField username;
    private javax.swing.JTextField withDrawAmountLimit;
    // End of variables declaration//GEN-END:variables
}
