/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Db.DatabaseQueries;
import Modal.Complains;

/**
 *
 * @author SSC
 */
public class ViewComplainFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewComplainFrame
     */
    public ViewComplainFrame() {
        initComponents();
    }

    public ViewComplainFrame(int complainId) {
        initComponents();
        Complains temp = DatabaseQueries.getComplainsDataById(complainId);
        complainDetail.setText(temp.getQuestions());
        complainRegistererDetails.setText(temp.getClientUsername() + " - " + temp.getAskedDate() + ":: " + temp.getAskedTime());
        if (temp.isIsAnswer()) {
            answerDetail.setText(temp.getAnswer());
            answerRegistererDetails.setText(temp.getAdminUserName() + " - " + temp.getAnswerDate() + ":: " + temp.getAnswerTime());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        complainDetail = new javax.swing.JTextArea();
        closeButton = new javax.swing.JButton();
        complainRegistererDetails = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        answerDetail = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        answerRegistererDetails = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 70)); // NOI18N
        jLabel5.setText("View Complain");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel14.setText("Answer");
        jLabel14.setToolTipText("Login");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 190, -1));

        complainDetail.setColumns(20);
        complainDetail.setRows(5);
        jScrollPane1.setViewportView(complainDetail);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 650, 110));

        closeButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 370, 40));

        complainRegistererDetails.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        complainRegistererDetails.setText("Complain");
        complainRegistererDetails.setToolTipText("Login");
        getContentPane().add(complainRegistererDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 430, -1));

        answerDetail.setColumns(20);
        answerDetail.setRows(5);
        jScrollPane2.setViewportView(answerDetail);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 650, 110));

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel16.setText("Complain");
        jLabel16.setToolTipText("Login");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 190, -1));

        answerRegistererDetails.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        answerRegistererDetails.setToolTipText("Login");
        getContentPane().add(answerRegistererDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 430, -1));

        backgroundImage.setText("jLabel1");
        getContentPane().add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewComplainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewComplainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewComplainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewComplainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewComplainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea answerDetail;
    private javax.swing.JLabel answerRegistererDetails;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextArea complainDetail;
    private javax.swing.JLabel complainRegistererDetails;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
